Refactor/improve validations
PetJournal/petjournal.api pull request #40
Opened 2023-09-11 22:01 UTC by andersonnaz

**Testes dos Validations**

**Descrição:**
Foram feitos testes para todos os validadores de entrada de dados.
Resolvido bug onde quebrava o código quando o valor passado nos parâmetros do body não eram do tipo string, quebrava o código retornando o um erro 500.

**Testes Realizados:**
Foram feitos testes em todos os arquivos, garantindo cobertura de 100%.

**Informações Adicionais:**
As Classes PasswordValidation e CompareFieldsValidation recebe um customError que é utilizado para retornar um erro diferente, é realmente necessário deixar aberto para utilizar um erro customizado?

2023-09-13 12:50 UTC, rodrigofmeneses commented on src/application/validation/validators/password-validation.ts
>        if (this.customError) {
About custom error, I think that this is important to return more descriptive error for caller. On body validation an "InvalidParamError" is too generic, just means that the param is not an string or is not provided. For example, password validation case we need show to caller that params are correctly sended but they missmatch in values.

2023-09-13 12:52 UTC, rodrigofmeneses commented on tests/src/application/validation/validators/email-validation.spec.ts
> +    const result = sut.validate({ fieldName: 11 })
to be more descriptive you can use an name for this value 11. Like `notStringValue = 11`

2023-09-13 12:53 UTC, rodrigofmeneses commented on tests/src/application/validation/validators/email-validation.spec.ts
> +    const result = sut.validate({ fieldName: 'invalid_email@mail.com' })
Same here. Maybe you want avoid hardcoded strings and use variables or values with better descriptions

2023-09-13 12:54 UTC, rodrigofmeneses commented on tests/src/application/validation/validators/name-validation.spec.ts
> +    const result = sut.validate({ fieldName: 11 })
Same in this file.
https://github.com/PetJournal/petjournal.api/pull/40#discussion_r1324466939

2023-09-13 13:02 UTC, rodrigofmeneses commented on tests/src/application/validation/validators/name-validation.spec.ts
> +  it('should returns invalidParamError if fieldName is not a string', () => {
I usualy group tests by dependency. For example, `NameValidation` has two dependencies, `fieldName` and `nameValidator`, so I think that is interesting make two groups. You can create this "dependencies groups" with `describe('NameOfGroup', => {...})`. It's not a strict rule, but usualy when we use the Stub, like `nameValidatorStub`, we are in group of `nameValidator`. What you think?

2023-09-13 13:06 UTC, rodrigofmeneses commented on tests/src/application/validation/validators/name-validation.spec.ts
> +    const result = sut.validate({ fieldName: 'valid_name' })
The object `{ fieldName: 'valid_name' }` it is used many times, maybe you consider create a global object. When you need change the value or be explicit of intention like 'invalid_name', you can use other object or overwrite.

2023-09-13 13:15 UTC, rodrigofmeneses commented on tests/src/application/validation/validators/password-validation.spec.ts
> +const makePasswordValidatorStub = (): PasswordValidator => {
We have a proper folder to group the Stubs and make test file more clean, specially if you will reutilize, check it

2023-09-13 13:17 UTC, rodrigofmeneses commented on tests/src/application/validation/validators/required-field-validation.spec.ts
> +    const result = sut.validate({ fieldName: '' })
You can test when a empty object is sended too.

2023-09-13 13:20 UTC, rodrigofmeneses requested changes
Very good job, consider the refactors to improve organization, but the logic is excelent.

2023-09-15 01:08 UTC, andersonnaz commented on tests/src/application/validation/validators/name-validation.spec.ts
> +  it('should returns invalidParamError if fieldName is not a string', () => {
sure, it's make sense.

2023-09-20 12:53 UTC, rodrigofmeneses approved these changes
LGFM

2023-09-20 12:53 UTC, rodrigofmeneses approved these changes
LGFM

2023-09-22 16:13 UTC, matheusgondra approved these changes
LGTM

2023-09-22 16:13 UTC, matheusgondra approved these changes
LGTM

2023-09-23 11:33 UTC, merged