Feature/pet name gender
PetJournal/petjournal.api pull request #44
Opened 2023-10-25 02:26 UTC by matheusgondra

Updating the `/pet` route with the `petName` and `gender` fields.

2023-10-25 12:26 UTC, rodrigofmeneses commented on src/infra/repos/postgresql/prisma/schema.prisma
> +  gender      String
What do you think about define this information with ENUM? Postgress support this feature.

2023-10-25 16:15 UTC, rodrigofmeneses commented on src/main/docs/schemas/pet-schema.ts
> +    gender: { type: 'string' }
Same that here: 
https://github.com/PetJournal/petjournal.api/pull/44#discussion_r1372019338

2023-10-26 00:09 UTC, rodrigofmeneses requested changes
Some problems:
- Missing pet-gender-validation tests
- Error in pet-gender-validation with type different of string.

2023-10-26 00:09 UTC, rodrigofmeneses requested changes
Some problems:
- Missing pet-gender-validation tests
- Error in pet-gender-validation with type different of string.

2023-10-31 17:59 UTC, rodrigofmeneses approved these changes
LGFM

2023-11-02 12:01 UTC, andersonnaz commented on src/application/validation/validators/pet-gender-validation.ts
> +    private readonly fieldName: string
we gonna use this patter?

2023-11-02 12:11 UTC, matheusgondra commented on src/application/validation/validators/pet-gender-validation.ts
> +    private readonly fieldName: string
I believe so, because this is a conversion used in typescript to write fewer lines of code and which doesn't make it difficult to read. Frameworks like Angular and NestJS use it too. And since we have typescript typing, there's no risk of passing the dependencies in the wrong order. @rodrigofmeneses, do you have anything against it?

2023-11-02 12:29 UTC, andersonnaz reviewed
good job, it's realy good. congratulations. I think that you forgot to update the example in the docs of the route /pet.

2023-11-02 12:31 UTC, andersonnaz commented on src/application/validation/validators/pet-gender-validation.ts
> +    private readonly fieldName: string
ok, to me is not a problem.

2023-11-02 16:12 UTC, andersonnaz approved these changes

2023-11-02 16:12 UTC, merged