Feature/update pet
PetJournal/petjournal.api pull request #48
Opened 2024-01-13 11:50 UTC by andersonnaz

Create breed and size Entity models
Create Breed and Size Repository
Create AppointPet use case to compile all use cases(specieAppoint, breedAppoint, sizeAppoint) at the same place.
Update Addpet including breed and size
Update breed seed with some new breeds
Update size seed with some new sizes

2024-01-15 18:01 UTC, matheusgondra requested changes

2024-01-15 18:01 UTC, matheusgondra commented on tests/src/data/use-cases/pet/db-add-pet.spec.ts
> +  // })
Remove this commented test

2024-01-15 18:01 UTC, matheusgondra commented on tests/src/data/use-cases/pet/db-appoint-breed.spec.ts
Replace the `test` function in jest with the `it` function, as this is the one we are using by convention

2024-01-15 18:01 UTC, matheusgondra commented on tests/src/data/use-cases/pet/db-appoint-breed.spec.ts
Put the test description in capital letters at the beginning of the sentence

2024-01-15 18:01 UTC, matheusgondra commented on tests/src/data/use-cases/pet/db-appoint-pet.spec.ts
Replace the test function in jest with the it function, as this is the one we are using by convention. Put the test description in capital letters at the beginning of the sentence

2024-01-15 18:01 UTC, matheusgondra commented on tests/src/data/use-cases/pet/db-appoint-pet.spec.ts
> +      }
This piece of code could be moved to a separate function to remove code repetition in other tests

2024-01-15 18:01 UTC, matheusgondra commented on tests/src/application/validation/validators/size-validation.spec.ts
Replace the test function in jest with the it function, as this is the one we are using by convention. Put the test description in capital letters at the beginning of the sentence

2024-01-15 18:01 UTC, matheusgondra commented on tests/src/application/validation/validators/breed-validation.spec.ts
Replace the test function in jest with the it function, as this is the one we are using by convention. Put the test description in capital letters at the beginning of the sentence

2024-01-15 21:05 UTC, rodrigofmeneses commented on src/application/validation/validators/breed-validation.ts
> +import { type BreedValidator } from '../protocols/breed-validator'
follow "@/app..." pattern

2024-01-16 21:01 UTC, andersonnaz commented on tests/src/data/use-cases/pet/db-appoint-breed.spec.ts
actually, this file is not be using, it's better to the code, remove it.

2024-01-19 11:36 UTC, rodrigofmeneses submitted a review, later dismissed
LGFM

2024-01-19 11:36 UTC, rodrigofmeneses commented on src/application/validation/validators/size-validation.ts
> +import { type SizeValidator } from '../protocols'
here too
https://github.com/PetJournal/petjournal.api/pull/48/files#r1452743285

2024-01-19 11:36 UTC, rodrigofmeneses commented on src/data/use-cases/pet/db-appoint-pet.ts
> +  private readonly sizeRepository: LoadSpecieByNameRepository
`LoadSpecieByNameRepository` is duplicated

2024-01-22 15:30 UTC, matheusgondra approved these changes

2024-01-22 15:32 UTC, rodrigofmeneses approved these changes
LGFM

2024-01-22 15:33 UTC, merged