Guardian Register
PetJournal/petjournal.api pull request #5
Opened 2023-04-17 15:13 UTC by dansenpir

Introduces the tutor registration feature.

2023-04-17 21:33 UTC, matheusgondra commented on src/data/protocols/add-guardian-repository.ts
> +  export type Result = boolean
Por que aqui foi usado o `type` e não `interface`? Se não há diferença acho que ficaria melhor usar `interface` para ficar padrão.

2023-04-17 22:05 UTC, matheusgondra commented on src/data/use-cases/db-add-guardian.ts
> +import { type AddGuardian } from '../../domain/use-cases'
Troca o caminho de importação para `import { type AddGuardian } from 'domain/use-cases'` já que o está apontando para a raíz do projeto configurada no typescript.

2023-04-17 22:07 UTC, matheusgondra commented on src/infra/criptography/bcrypt-adapter.ts
> +import { type Encrypter } from '../../../src/data/protocols'
Troca o caminho de importação para `import { type Encrypter } from 'data/protocols'` já que a importação está apontando para a raíz do projeto configurada no typescript.

2023-04-17 22:12 UTC, matheusgondra commented on src/main/adapters/express-route-adapter.ts
> +import { type Controller } from '../../application/controllers/controller'
Troca a importação para `import { type Controller } from 'application/controllers/controller'` já que a importação está apontando para a raíz do projeto configurada no typescript.

2023-04-17 22:13 UTC, matheusgondra commented on src/main/adapters/express-route-adapter.ts
> +import { type HttpResponse, type HttpRequest } from '../../application/helpers/http'
Trocar a importação para `import { type HttpResponse, type HttpRequest } from 'application/helpers/http'` já que a importação está apontando para a raíz do projeto configurada no typescript.

2023-04-17 22:20 UTC, matheusgondra commented on src/main/factories/controllers/signup-controller-factory.ts
> +
Remover os "../../../" dos imports, pois já está configurado a pasta `src` como a raíz do projeto no typescript

```ts
import { EmailValidatorAdapter, NameValidatorAdapter, PasswordValidatorAdapter, PhoneValidatorAdapter } from 'application/validation/validators'
import { SignUpController } from 'application/controllers/signup'
import { DbAddGuardian } from 'data/use-cases/db-add-guardian'
import { BcryptAdapter } from 'infra/criptography/bcrypt-adapter'
import { GuardianAccountRepository } from 'infra/repos/postgresql/guardian-account-repository'
```

2023-04-18 13:10 UTC, matheusgondra commented on tests/application/controllers/signup.spec.ts
> +import { type PhoneValidator, type EmailValidator, type NameValidator } from '../../../src/application/validation/protocols'
Remove the "../../../src/" from the imports, because the `src` folder is already set as the root of the project in typescript

2023-04-18 13:41 UTC, matheusgondra commented on tests/data/use-cases/db-add-guardian.spec.ts
> +import { type Guardian } from '../../../src/domain/entities'
this path and this import do not exist

2023-04-18 13:42 UTC, matheusgondra commented on tests/data/use-cases/db-add-guardian.spec.ts
> +import { DbAddGuardian } from '../../../src/data/use-cases'
Remove the "../../../src/" from the imports, because the `src` folder is already set as the root of the project in typescript

2023-04-18 13:44 UTC, matheusgondra commented on tests/data/use-cases/db-add-guardian.spec.ts
> +import { type IAddGuardian } from '../../../src/domain/use-cases'
Remove the "../../../src" and correct the interface name

2023-04-18 13:55 UTC, matheusgondra commented on tests/infra/repos/postgresql/guardian-account.spec.ts
> +import { GuardianAccountRepository } from '../../../../src/infra/repos/postgresql/guardian-account-repository'
Remove "../../../src/" from import, because the `src` folder is already set as the root of the project in typescript

2023-04-18 13:56 UTC, matheusgondra commented on tests/main/middlewares/body-parser.test.ts
> +import app from '../../../src/main/config/app'
Remove "../../../src/" from import, because the `src` folder is already set as the root of the project in typescript

2023-04-18 13:58 UTC, matheusgondra commented on tests/main/middlewares/content-type.test.ts
> +import app from '../../../src/main/config/app'
Remove "../../../src/" from import, because the `src` folder is already set as the root of the project in typescript

2023-04-18 14:00 UTC, matheusgondra commented on tests/main/middlewares/cors.test.ts
> +import app from '../../../src/main/config/app'
Remove "../../../src/" from import, because the `src` folder is already set as the root of the project in typescript

2023-04-18 14:00 UTC, matheusgondra commented on tests/main/routes/signup-routes.test.ts
> +import app from '../../../src/main/config/app'
Remove "../../../src/" from import, because the `src` folder is already set as the root of the project in typescript

2023-04-18 14:07 UTC, matheusgondra commented on tests/validation/name-validator-adapter.spec.ts
> +import { NameValidatorAdapter } from '../../src/application/validation/validators'
Remove "../../../src/" from import, because the `src` folder is already set as the root of the project in typescript

2023-04-18 14:08 UTC, matheusgondra commented on tests/validation/password-validator-adapter.spec.ts
> +import { PasswordValidatorAdapter } from '../../src/application/validation/validators/'
Remove "../../../src/" from import, because the `src` folder is already set as the root of the project in typescript

2023-04-18 14:09 UTC, matheusgondra commented on tests/validation/phone-validator-adapter.spec.ts
> +import { PhoneValidatorAdapter } from '../../src/application/validation/validators'
Remove "../../../src/" from import, because the `src` folder is already set as the root of the project in typescript

2023-04-18 14:26 UTC, matheusgondra requested changes
Review the commented out code

2023-04-18 14:59 UTC, maztt requested changes
Code clarity requested changes

2023-04-19 14:25 UTC, dansenpir commented on src/application/controllers/signup.ts
Yes, in the future this piece of code will need refactoring.

2023-04-19 15:38 UTC, matheusgondra approved these changes

2023-04-19 15:42 UTC, maztt approved these changes

2023-04-19 18:27 UTC, merged