Feature/route size
PetJournal/petjournal.api pull request #50
Opened 2024-01-30 01:23 UTC by andersonnaz

create dog and cat size repository
create dog and cat size factory
create dog and cat size routes
create dog and cat size routes tests
update doc

2024-02-02 10:52 UTC, matheusgondra requested changes

2024-02-02 10:52 UTC, matheusgondra commented on tests/src/application/controllers/pets/sizes/load-cat.spec.ts
Change the test function to `it()`. Start the test description with a capital letter

2024-02-02 10:52 UTC, matheusgondra commented on tests/src/application/controllers/pets/sizes/load-dog.spec.ts
Change the test function to `it()`. Start the test description with a capital letter

2024-02-02 11:21 UTC, rodrigofmeneses commented on src/data/protocols/db/size/load-cat-sizes-repository.ts
> +  export type Result = Size[] | undefined
Maybe undefined is not necessary.

2024-02-02 11:24 UTC, rodrigofmeneses commented on src/main/factories/controllers/pet/load-cat-sizes-factory.ts
> +import { makeDbLoadCatSizes } from '../../usecases'
@ patterns

2024-02-02 11:41 UTC, rodrigofmeneses commented on tests/src/data/use-cases/pet/size/db-load-cat-sizes.spec.ts
> +    it('Should return undefined if sizeRepository returns undefined', async () => {
why repository returns undefined?

2024-02-02 11:42 UTC, rodrigofmeneses reviewed
nice work

2024-02-05 16:05 UTC, matheusgondra requested changes

2024-02-05 16:05 UTC, matheusgondra commented on src/infra/repos/postgresql/breed-repository.ts
>    }
I believe it can be returned directly, because if it's empty it will already return an empty array and if it has something it will return the data

2024-02-05 16:05 UTC, matheusgondra commented on src/infra/repos/postgresql/size-repository.ts
> +  }
I believe it can be returned directly, because if it's empty it will already return an empty array and if it has something it will return the data

2024-02-05 17:39 UTC, rodrigofmeneses approved these changes
LGFM

2024-02-05 18:22 UTC, matheusgondra approved these changes

2024-02-05 18:27 UTC, merged