Feature/load pets by guardian
PetJournal/petjournal.api pull request #55
Opened 2024-05-20 22:16 UTC by andersonnaz

create LoadPets use case
create LoadPets Controller
create route /pet with method GET to return a list of pets by Guardian
create tests for all features like usecase, controller and route
update documentation with new route.

2024-05-21 15:37 UTC, matheusgondra commented
Está faltando os testes do `LoadPetsController`

2024-05-21 15:41 UTC, matheusgondra commented on tests/src/infra/repos/postgresql/pet-repository.spec.ts
> +      expect(result).toBeTruthy()
Esse expect não é necessário já que está testando com o `toEqual()` na linha abaixo

2024-05-28 15:45 UTC, matheusgondra requested changes

2024-05-28 15:45 UTC, matheusgondra commented on tests/src/application/controllers/pets/load-pets.spec.ts
Create a test that checks the `LoadPets` call inside the controller

2024-05-28 15:47 UTC, matheusgondra reviewed
I think we should test the return case when there are no pets registered. Test an empty list return or return a 204 status from noContent

2024-06-03 15:52 UTC, rodrigofmeneses submitted a review, later dismissed
LGFM

2024-06-03 16:15 UTC, rodrigofmeneses approved these changes

2024-06-03 16:39 UTC, matheusgondra approved these changes

2024-06-03 17:26 UTC, merged